### ISSUE TITLE
Can't install from Automatic1111

### ISSUE THREAD

**Issue by DmytroSokhach** [AlUlkesh/sd_grid_add_image_number#1]
Tried to install from Extensions tab and got error:

``` python
Error completing request
Arguments: ('https://github.com/AlUlkesh/sd_grid_add_image_number.git', ['localization'], 0) {}
Traceback (most recent call last):
  File "D:\Dev\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Dev\stable-diffusion-webui\modules\ui_extensions.py", line 166, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "D:\Dev\stable-diffusion-webui\modules\ui_extensions.py", line 140, in install_extension_from_url
    repo = git.Repo.clone_from(url, tmpdir)
  File "D:\Dev\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "D:\Dev\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "D:\Dev\stable-diffusion-webui\venv\lib\site-packages\git\util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "D:\Dev\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/AlUlkesh/sd_grid_add_image_number.git D:\Dev\stable-diffusion-webui\tmp\sd_grid_add_image_number
  stderr: 'Cloning into 'D:\Dev\stable-diffusion-webui\tmp\sd_grid_add_image_number'...
fatal: unable to access 'https://github.com/AlUlkesh/sd_grid_add_image_number.git/': Recv failure: Connection was reset
```

Not sure if it should be reported here, or in https://github.com/AUTOMATIC1111/stable-diffusion-webui ?

ReadMe line from bottom of the page also fails, it has redundant "/" in https link
`git clone https://github.com/AlUlkesh/sd_grid_add_image_number/ extensions/sd_grid_add_image_number`
should be
`git clone https://github.com/AlUlkesh/sd_grid_add_image_number extensions/sd_grid_add_image_number`

**Comment by AlUlkesh** [comment]
> ReadMe line from bottom of the page also fails, it has redundant "/" in https link

I don't think that's it. Works for me and according to the git docs, final slash is correct:
```
Git supports ssh, git, http, and https protocols (in addition, ftp, and ftps can be used for fetching, but this is inefficient and deprecated; do not use it).
The native transport (i.e. git:// URL) does no authentication and should be used with caution on unsecured networks.
The following syntaxes may be used with them:
ssh://[user@]host.xz[:port]/path/to/repo.git/
git://host.xz[:port]/path/to/repo.git/
http[s]://host.xz[:port]/path/to/repo.git/
ftp[s]://host.xz[:port]/path/to/repo.git/
```
https://git-scm.com/docs/git-clone

Can you currently install any other new extension?
