### ISSUE TITLE
try to get xyz_plot info from State when not using xyz plot

### ISSUE THREAD

**Issue by SLAPaper** [AlUlkesh/sd_grid_add_image_number#13]
getting this error when runing normal txt2img grid:
```
*** Error executing callback image_saved_callback for C:\Users\SLAPaper\workspace\stable-diffusion-webui\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py
    Traceback (most recent call last):
      File "C:\Users\SLAPaper\workspace\stable-diffusion-webui\modules\script_callbacks.py", line 200, in image_saved_callback
        c.callback(params)
      File "C:\Users\SLAPaper\workspace\stable-diffusion-webui\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 99, in handle_image_saved
        img_label_x, img_key_x, img_value_x = getaxis_infos(params.p, state.xyz_plot_x)
    AttributeError: 'State' object has no attribute 'xyz_plot_x'
```

it seems that the plugin fail to check wheather xyz plot is actually running

**Comment by AlUlkesh** [comment]
Oops... should be fixed now!

**Comment by SLAPaper** [comment]
Thanks!
