### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sd_model'

### ISSUE THREAD

**Issue by freezerain** [AlUlkesh/sd_grid_add_image_number#9]
```
Error executing callback image_saved_callback for D:\Projects\SD Portrait Generator\stable-diffusion-webui\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py
Traceback (most recent call last):
  File "D:\Projects\SD Portrait Generator\stable-diffusion-webui\modules\script_callbacks.py", line 185, in image_saved_callback
    c.callback(params)
  File "D:\Projects\SD Portrait Generator\stable-diffusion-webui\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 84, in handle_image_saved
    getaxis_value(params.p, img_filename, "xyz_plot_x")
  File "D:\Projects\SD Portrait Generator\stable-diffusion-webui\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 61, in getaxis_value
    axis_value = os.path.basename(p.sd_model.sd_model_checkpoint)
AttributeError: 'NoneType' object has no attribute 'sd_model'
```
While doung X/Y matrix with different checkpoints in X, this error poping up in logs for each generated pic.
Nothing else is affected, reporting just in case
Have a nice day

**Comment by AlUlkesh** [comment]
Thanks! It was trying to get the xyz info for the grid image also. Should work now.
